### ISSUE TITLE
Genereate seed number

### ISSUE THREAD

**Issue by FrodeMMeling** [rchouinard/rych-otp#5]
Do you have a function to generate a Seed number.
Like this number here
```
protected function setUp()
    {
        $this->seed = new Seed('3132333435363738393031323334353637383930');
    }
```

**Comment by rchouinard** [comment]
You can use `$this->seed = Seed::generate();` if you just need a random seed. If you need a fixed seed, then constructing the seed manually as you did is the best method.

The prototype for the function is `Rych\OTP\Seed::generate($bytes = 20, \Rych\Random\Random = $random = null)`, so by default it will generate a 20-byte random string using the best random source available. If you need to use this method but want a fixed value, you can use the following:

```php
<?php

use Rych\Random\Random;
use Rych\Random\Generator\MockGenerator;
use Rych\OTP\Seed;

$generator = new MockGenerator();
$generator->setMockString("myrandomdata");
$random = new Random($generator);

$seed = Seed::generate(20, $random);
```

This will result in an instance of `Rych\OTP\Seed` with a value of 'myrandomdatamyrandom'.

**Comment by rchouinard** [comment]
I assume my previous comment solved the problem. Closing this issue.
