### ISSUE TITLE
Please Use Identical Comparison For Validation

### ISSUE THREAD

**Issue by khandar-william** [rchouinard/rych-otp#6]
In the HOTP class, you use the equals operator to validate the OTP
```
if ($otp == $this->calculate($current)) {
```
Could you please use the identical operator `===`? 
[This article](https://blog.whitehatsec.com/magic-hashes/) explains one of the danger of using `==` operator when comparing important strings.

**Comment by Ennosuke** [comment]
I changed my pull request to factor this in so it's more meaningfull. I hope you are okay with that.

**Comment by b3nl** [comment]
+1
